### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by nahudev01** [josueluque/rest-api#1]
Para que sirve el archivo [requirements.txt](https://github.com/josueluque/rest-api/blob/main/requirements.txt)?

**Comment by josueluque** [comment]
Hola @ngarcia-dev , 
El archivo requirements.txt es utilizado para enumerar todas las dependencias del proyecto y sus versiones correspondientes. Es importante este archivo ya que ayuda a gestionar las dependencias del proyecto y se garantiza la reproducibilidad del mismo.
